[package]
name = "lib_image"
version = "0.1.0"
edition = "2021"

[dependencies]
lib_core = { path = "../lib_core" }
magick_rust = { git = "https://github.com/nlfiedler/magick-rust", rev = "dfd8df0dd102348c23b33bfc946a9d70b5db25bf" }